let cleanedRepresentatives = [ 
{ name: 'Ralph Abraham',
state: 'LA',
district: '5',
party: 'R',
twitter_account: 'RepAbraham',
url: 'https://abraham.house.gov',
title: 'Representative' },
{ name: 'Alma Adams',
state: 'NC',
district: '12',
party: 'D',
twitter_account: 'RepAdams',
url: 'https://adams.house.gov',
title: 'Representative' },
{ name: 'Robert Aderholt',
state: 'AL',
district: '4',
party: 'R',
twitter_account: 'Robert_Aderholt',
url: 'https://aderholt.house.gov',
title: 'Representative' },
{ name: 'Pete Aguilar',
state: 'CA',
district: '31',
party: 'D',
twitter_account: 'reppeteaguilar',
url: 'https://aguilar.house.gov',
title: 'Representative' },
{ name: 'Rick Allen',
state: 'GA',
district: '12',
party: 'R',
twitter_account: 'reprickallen',
url: 'https://allen.house.gov',
title: 'Representative' },
{ name: 'Colin Allred',
state: 'TX',
district: '32',
party: 'D',
twitter_account: 'RepColinAllred',
url: 'https://allred.house.gov/',
title: 'Representative' },
{ name: 'Justin Amash',
state: 'MI',
district: '3',
party: 'R',
twitter_account: null,
url: 'https://amash.house.gov',
title: 'Representative' },
{ name: 'Justin Amash',
state: 'MI',
district: '3',
party: 'I',
twitter_account: null,
url: 'https://amash.house.gov',
title: 'Representative' },
{ name: 'Mark Amodei',
state: 'NV',
district: '2',
party: 'R',
twitter_account: 'MarkAmodeiNV2',
url: 'https://amodei.house.gov',
title: 'Representative' },
{ name: 'Kelly Armstrong',
state: 'ND',
district: 'At-Large',
party: 'R',
twitter_account: 'RepArmstrongND',
url: 'https://armstrong.house.gov/',
title: 'Representative' },
{ name: 'Jodey Arrington',
state: 'TX',
district: '19',
party: 'R',
twitter_account: 'RepArrington',
url: 'https://arrington.house.gov',
title: 'Representative' },
{ name: 'Cynthia Axne',
state: 'IA',
district: '3',
party: 'D',
twitter_account: 'RepCindyAxne',
url: 'https://axne.house.gov/',
title: 'Representative' },
{ name: 'Brian Babin',
state: 'TX',
district: '36',
party: 'R',
twitter_account: 'RepBrianBabin',
url: 'https://babin.house.gov',
title: 'Representative' },
{ name: 'Don Bacon',
state: 'NE',
district: '2',
party: 'R',
twitter_account: 'repdonbacon',
url: 'https://bacon.house.gov',
title: 'Representative' },
{ name: 'James Baird',
state: 'IN',
district: '4',
party: 'R',
twitter_account: 'RepJimBaird',
url: 'https://baird.house.gov/',
title: 'Representative' },
{ name: 'Troy Balderson',
state: 'OH',
district: '12',
party: 'R',
twitter_account: 'RepBalderson',
url: 'https://balderson.house.gov/',
title: 'Representative' },
{ name: 'Jim Banks',
state: 'IN',
district: '3',
party: 'R',
twitter_account: 'RepJimBanks',
url: 'https://banks.house.gov',
title: 'Representative' },
{ name: 'Andy Barr',
state: 'KY',
district: '6',
party: 'R',
twitter_account: 'RepAndyBarr',
url: 'https://barr.house.gov',
title: 'Representative' },
{ name: 'Nanette Barragán',
state: 'CA',
district: '44',
party: 'D',
twitter_account: 'RepBarragan',
url: 'https://barragan.house.gov',
title: 'Representative' },
{ name: 'Karen Bass',
state: 'CA',
district: '37',
party: 'D',
twitter_account: 'RepKarenBass',
url: 'https://bass.house.gov',
title: 'Representative' },
{ name: 'Joyce Beatty',
state: 'OH',
district: '3',
party: 'D',
twitter_account: 'RepBeatty',
url: 'https://beatty.house.gov',
title: 'Representative' },
{ name: 'Ami Bera',
state: 'CA',
district: '7',
party: 'D',
twitter_account: 'RepBera',
url: 'https://bera.house.gov',
title: 'Representative' },
{ name: 'Jack Bergman',
state: 'MI',
district: '1',
party: 'R',
twitter_account: 'RepJackBergman',
url: 'https://bergman.house.gov',
title: 'Representative' },
{ name: 'Donald Beyer',
state: 'VA',
district: '8',
party: 'D',
twitter_account: 'RepDonBeyer',
url: 'https://beyer.house.gov',
title: 'Representative' },
{ name: 'Andy Biggs',
state: 'AZ',
district: '5',
party: 'R',
twitter_account: 'RepAndyBiggsAZ',
url: 'https://biggs.house.gov',
title: 'Representative' },
{ name: 'Gus Bilirakis',
state: 'FL',
district: '12',
party: 'R',
twitter_account: 'RepGusBilirakis',
url: 'https://bilirakis.house.gov',
title: 'Representative' },
{ name: 'Sanford Bishop',
state: 'GA',
district: '2',
party: 'D',
twitter_account: 'SanfordBishop',
url: 'https://bishop.house.gov',
title: 'Representative' },
{ name: 'Rob Bishop',
state: 'UT',
district: '1',
party: 'R',
twitter_account: 'RepRobBishop',
url: 'https://robbishop.house.gov',
title: 'Representative' },
{ name: 'Dan Bishop',
state: 'NC',
district: '9',
party: 'R',
twitter_account: 'RepDanBishop',
url: 'https://danbishop.house.gov/',
title: 'Representative' },
{ name: 'Earl Blumenauer',
state: 'OR',
district: '3',
party: 'D',
twitter_account: 'BlumenauerMedia',
url: 'https://blumenauer.house.gov',
title: 'Representative' },
{ name: 'Lisa Blunt Rochester',
state: 'DE',
district: 'At-Large',
party: 'D',
twitter_account: 'RepLBR',
url: 'https://bluntrochester.house.gov',
title: 'Representative' },
{ name: 'Suzanne Bonamici',
state: 'OR',
district: '1',
party: 'D',
twitter_account: 'RepBonamici',
url: 'https://bonamici.house.gov',
title: 'Representative' },
{ name: 'Mike Bost',
state: 'IL',
district: '12',
party: 'R',
twitter_account: 'RepBost',
url: 'https://bost.house.gov',
title: 'Representative' },
{ name: 'Brendan Boyle',
state: 'PA',
district: '2',
party: 'D',
twitter_account: 'CongBoyle',
url: 'https://boyle.house.gov',
title: 'Representative' },
{ name: 'Kevin Brady',
state: 'TX',
district: '8',
party: 'R',
twitter_account: 'RepKevinBrady',
url: 'https://kevinbrady.house.gov',
title: 'Representative' },
{ name: 'Anthony Brindisi',
state: 'NY',
district: '22',
party: 'D',
twitter_account: 'RepBrindisi',
url: 'https://brindisi.house.gov/',
title: 'Representative' },
{ name: 'Mo Brooks',
state: 'AL',
district: '5',
party: 'R',
twitter_account: 'RepMoBrooks',
url: 'https://brooks.house.gov',
title: 'Representative' },
{ name: 'Susan Brooks',
state: 'IN',
district: '5',
party: 'R',
twitter_account: 'SusanWBrooks',
url: 'https://susanwbrooks.house.gov',
title: 'Representative' },
{ name: 'Anthony Brown',
state: 'MD',
district: '4',
party: 'D',
twitter_account: 'RepAnthonyBrown',
url: 'https://anthonybrown.house.gov',
title: 'Representative' },
{ name: 'Julia Brownley',
state: 'CA',
district: '26',
party: 'D',
twitter_account: 'RepBrownley',
url: 'https://juliabrownley.house.gov',
title: 'Representative' },
{ name: 'Vern Buchanan',
state: 'FL',
district: '16',
party: 'R',
twitter_account: 'VernBuchanan',
url: 'https://buchanan.house.gov',
title: 'Representative' },
{ name: 'Ken Buck',
state: 'CO',
district: '4',
party: 'R',
twitter_account: 'RepKenBuck',
url: 'https://buck.house.gov',
title: 'Representative' },
{ name: 'Larry Bucshon',
state: 'IN',
district: '8',
party: 'R',
twitter_account: 'RepLarryBucshon',
url: 'https://bucshon.house.gov',
title: 'Representative' },
{ name: 'Ted Budd',
state: 'NC',
district: '13',
party: 'R',
twitter_account: 'RepTedBudd',
url: 'https://budd.house.gov',
title: 'Representative' },
{ name: 'Tim Burchett',
state: 'TN',
district: '2',
party: 'R',
twitter_account: 'RepTimBurchett',
url: 'https://burchett.house.gov/',
title: 'Representative' },
{ name: 'Michael Burgess',
state: 'TX',
district: '26',
party: 'R',
twitter_account: 'MichaelCBurgess',
url: 'https://burgess.house.gov',
title: 'Representative' },
{ name: 'Cheri Bustos',
state: 'IL',
district: '17',
party: 'D',
twitter_account: 'RepCheri',
url: 'https://bustos.house.gov',
title: 'Representative' },
{ name: 'G. Butterfield',
state: 'NC',
district: '1',
party: 'D',
twitter_account: 'GKButterfield',
url: 'https://butterfield.house.gov',
title: 'Representative' },
{ name: 'Bradley Byrne',
state: 'AL',
district: '1',
party: 'R',
twitter_account: 'RepByrne',
url: 'https://byrne.house.gov',
title: 'Representative' },
{ name: 'Ken Calvert',
state: 'CA',
district: '42',
party: 'R',
twitter_account: 'KenCalvert',
url: 'https://calvert.house.gov',
title: 'Representative' },
{ name: 'Salud Carbajal',
state: 'CA',
district: '24',
party: 'D',
twitter_account: 'RepCarbajal',
url: 'https://carbajal.house.gov',
title: 'Representative' },
{ name: 'Tony Cárdenas',
state: 'CA',
district: '29',
party: 'D',
twitter_account: 'RepCardenas',
url: 'https://cardenas.house.gov',
title: 'Representative' },
{ name: 'André Carson',
state: 'IN',
district: '7',
party: 'D',
twitter_account: 'RepAndreCarson',
url: 'https://carson.house.gov',
title: 'Representative' },
{ name: 'John Carter',
state: 'TX',
district: '31',
party: 'R',
twitter_account: 'JudgeCarter',
url: 'https://carter.house.gov',
title: 'Representative' },
{ name: 'Buddy Carter',
state: 'GA',
district: '1',
party: 'R',
twitter_account: 'RepBuddyCarter',
url: 'https://buddycarter.house.gov',
title: 'Representative' },
{ name: 'Matt Cartwright',
state: 'PA',
district: '8',
party: 'D',
twitter_account: 'RepCartwright',
url: 'https://cartwright.house.gov',
title: 'Representative' },
{ name: 'Ed Case',
state: 'HI',
district: '1',
party: 'D',
twitter_account: 'RepEdCase',
url: 'https://case.house.gov',
title: 'Representative' },
{ name: 'Sean Casten',
state: 'IL',
district: '6',
party: 'D',
twitter_account: 'RepCasten',
url: 'https://casten.house.gov/',
title: 'Representative' },
{ name: 'Kathy Castor',
state: 'FL',
district: '14',
party: 'D',
twitter_account: 'USRepKCastor',
url: 'https://castor.house.gov',
title: 'Representative' },
{ name: 'Joaquín Castro',
state: 'TX',
district: '20',
party: 'D',
twitter_account: 'JoaquinCastrotx',
url: 'https://castro.house.gov',
title: 'Representative' },
{ name: 'Steven Chabot',
state: 'OH',
district: '1',
party: 'R',
twitter_account: 'RepSteveChabot',
url: 'https://chabot.house.gov',
title: 'Representative' },
{ name: 'Liz Cheney',
state: 'WY',
district: 'At-Large',
party: 'R',
twitter_account: 'RepLizCheney',
url: 'https://cheney.house.gov',
title: 'Representative' },
{ name: 'Judy Chu',
state: 'CA',
district: '27',
party: 'D',
twitter_account: 'RepJudyChu',
url: 'https://chu.house.gov',
title: 'Representative' },
{ name: 'David Cicilline',
state: 'RI',
district: '1',
party: 'D',
twitter_account: 'RepCicilline',
url: 'https://cicilline.house.gov',
title: 'Representative' },
{ name: 'Gilbert Cisneros',
state: 'CA',
district: '39',
party: 'D',
twitter_account: 'RepGilCisneros',
url: 'https://cisneros.house.gov/',
title: 'Representative' },
{ name: 'Katherine Clark',
state: 'MA',
district: '5',
party: 'D',
twitter_account: 'RepKClark',
url: 'https://katherineclark.house.gov',
title: 'Representative' },
{ name: 'Yvette Clarke',
state: 'NY',
district: '9',
party: 'D',
twitter_account: 'RepYvetteClarke',
url: 'https://clarke.house.gov',
title: 'Representative' },
{ name: 'William Clay',
state: 'MO',
district: '1',
party: 'D',
twitter_account: null,
url: 'https://lacyclay.house.gov',
title: 'Representative' },
{ name: 'Emanuel Cleaver',
state: 'MO',
district: '5',
party: 'D',
twitter_account: 'RepCleaver',
url: 'https://cleaver.house.gov',
title: 'Representative' },
{ name: 'Ben Cline',
state: 'VA',
district: '6',
party: 'R',
twitter_account: 'RepBenCline',
url: 'https://cline.house.gov/',
title: 'Representative' },
{ name: 'Michael Cloud',
state: 'TX',
district: '27',
party: 'R',
twitter_account: 'RepCloudTX',
url: 'https://cloud.house.gov/',
title: 'Representative' },
{ name: 'James Clyburn',
state: 'SC',
district: '6',
party: 'D',
twitter_account: 'WhipClyburn',
url: 'https://clyburn.house.gov',
title: 'Representative' },
{ name: 'Steve Cohen',
state: 'TN',
district: '9',
party: 'D',
twitter_account: 'RepCohen',
url: 'https://cohen.house.gov',
title: 'Representative' },
{ name: 'Tom Cole',
state: 'OK',
district: '4',
party: 'R',
twitter_account: 'TomColeOK04',
url: 'https://cole.house.gov',
title: 'Representative' },
{ name: 'Doug Collins',
state: 'GA',
district: '9',
party: 'R',
twitter_account: 'RepDougCollins',
url: 'https://dougcollins.house.gov',
title: 'Representative' },
{ name: 'Chris Collins',
state: 'NY',
district: '27',
party: 'R',
twitter_account: 'RepChrisCollins',
url: 'https://chriscollins.house.gov',
title: 'Representative' },
{ name: 'James Comer',
state: 'KY',
district: '1',
party: 'R',
twitter_account: null,
url: 'https://comer.house.gov',
title: 'Representative' },
{ name: 'K. Conaway',
state: 'TX',
district: '11',
party: 'R',
twitter_account: 'ConawayTX11',
url: 'https://conaway.house.gov',
title: 'Representative' },
{ name: 'Gerald Connolly',
state: 'VA',
district: '11',
party: 'D',
twitter_account: 'GerryConnolly',
url: 'https://connolly.house.gov',
title: 'Representative' },
{ name: 'Paul Cook',
state: 'CA',
district: '8',
party: 'R',
twitter_account: 'RepPaulCook',
url: 'https://cook.house.gov',
title: 'Representative' },
{ name: 'Jim Cooper',
state: 'TN',
district: '5',
party: 'D',
twitter_account: 'RepJimCooper',
url: 'https://cooper.house.gov',
title: 'Representative' },
{ name: 'J. Correa',
state: 'CA',
district: '46',
party: 'D',
twitter_account: 'reploucorrea',
url: 'https://correa.house.gov',
title: 'Representative' },
{ name: 'Jim Costa',
state: 'CA',
district: '16',
party: 'D',
twitter_account: 'RepJimCosta',
url: 'https://costa.house.gov',
title: 'Representative' },
{ name: 'Joe Courtney',
state: 'CT',
district: '2',
party: 'D',
twitter_account: 'RepJoeCourtney',
url: 'https://courtney.house.gov',
title: 'Representative' },
{ name: 'TJ Cox',
state: 'CA',
district: '21',
party: 'D',
twitter_account: 'RepTjCox',
url: 'https://cox.house.gov/',
title: 'Representative' },
{ name: 'Angie Craig',
state: 'MN',
district: '2',
party: 'D',
twitter_account: 'RepAngieCraig',
url: 'https://craig.house.gov/',
title: 'Representative' },
{ name: 'Rick Crawford',
state: 'AR',
district: '1',
party: 'R',
twitter_account: 'RepRickCrawford',
url: 'https://crawford.house.gov',
title: 'Representative' },
{ name: 'Dan Crenshaw',
state: 'TX',
district: '2',
party: 'R',
twitter_account: 'RepDanCrenshaw',
url: 'https://crenshaw.house.gov/',
title: 'Representative' },
{ name: 'Charlie Crist',
state: 'FL',
district: '13',
party: 'D',
twitter_account: 'repcharliecrist',
url: 'https://crist.house.gov',
title: 'Representative' },
{ name: 'Jason Crow',
state: 'CO',
district: '6',
party: 'D',
twitter_account: 'RepJasonCrow',
url: 'https://crow.house.gov/',
title: 'Representative' },
{ name: 'Henry Cuellar',
state: 'TX',
district: '28',
party: 'D',
twitter_account: 'RepCuellar',
url: 'https://cuellar.house.gov',
title: 'Representative' },
{ name: 'Elijah Cummings',
state: 'MD',
district: '7',
party: 'D',
twitter_account: 'RepCummings',
url: 'https://cummings.house.gov',
title: 'Representative' },
{ name: 'Joe Cunningham',
state: 'SC',
district: '1',
party: 'D',
twitter_account: 'RepCunningham',
url: 'https://cunningham.house.gov/',
title: 'Representative' },
{ name: 'John Curtis',
state: 'UT',
district: '3',
party: 'R',
twitter_account: 'RepJohnCurtis',
url: 'https://curtis.house.gov',
title: 'Representative' },
{ name: 'Sharice Davids',
state: 'KS',
district: '3',
party: 'D',
twitter_account: 'RepDavids',
url: 'https://davids.house.gov/',
title: 'Representative' },
{ name: 'Warren Davidson',
state: 'OH',
district: '8',
party: 'R',
twitter_account: 'WarrenDavidson',
url: 'https://davidson.house.gov',
title: 'Representative' },
{ name: 'Susan Davis',
state: 'CA',
district: '53',
party: 'D',
twitter_account: 'RepSusanDavis',
url: 'https://susandavis.house.gov',
title: 'Representative' },
{ name: 'Rodney Davis',
state: 'IL',
district: '13',
party: 'R',
twitter_account: 'RodneyDavis',
url: 'https://rodneydavis.house.gov',
title: 'Representative' },
{ name: 'Danny Davis',
state: 'IL',
district: '7',
party: 'D',
twitter_account: 'RepDannyDavis',
url: 'https://davis.house.gov',
title: 'Representative' }, 

{ name: 'Peter DeFazio',
state: 'OR',
district: '4',
party: 'D',
twitter_account: 'RepPeterDeFazio',
url: 'https://defazio.house.gov',
title: 'Representative' },
{ name: 'Diana DeGette',
state: 'CO',
district: '1',
party: 'D',
twitter_account: 'RepDianaDeGette',
url: 'https://degette.house.gov',
title: 'Representative' },
{ name: 'Rosa DeLauro',
state: 'CT',
district: '3',
party: 'D',
twitter_account: 'RosaDeLauro',
url: 'https://delauro.house.gov',
title: 'Representative' },
{ name: 'Suzan DelBene',
state: 'WA',
district: '1',
party: 'D',
twitter_account: 'RepDelBene',
url: 'https://delbene.house.gov',
title: 'Representative' },
{ name: 'Antonio Delgado',
state: 'NY',
district: '19',
party: 'D',
twitter_account: 'repdelgado',
url: 'https://delgado.house.gov/',
title: 'Representative' },
{ name: 'Val Demings',
state: 'FL',
district: '10',
party: 'D',
twitter_account: 'RepValDemings',
url: 'https://demings.house.gov',
title: 'Representative' },
{ name: 'Mark DeSaulnier',
state: 'CA',
district: '11',
party: 'D',
twitter_account: 'RepDeSaulnier',
url: 'https://desaulnier.house.gov',
title: 'Representative' },
{ name: 'Scott DesJarlais',
state: 'TN',
district: '4',
party: 'R',
twitter_account: 'DesJarlaisTN04',
url: 'https://desjarlais.house.gov',
title: 'Representative' },
{ name: 'Ted Deutch',
state: 'FL',
district: '22',
party: 'D',
twitter_account: 'RepTedDeutch',
url: 'https://teddeutch.house.gov',
title: 'Representative' },
{ name: 'Mario Diaz-Balart',
state: 'FL',
district: '25',
party: 'R',
twitter_account: 'MarioDB',
url: 'https://mariodiazbalart.house.gov',
title: 'Representative' },
{ name: 'Debbie Dingell',
state: 'MI',
district: '12',
party: 'D',
twitter_account: 'RepDebDingell',
url: 'https://debbiedingell.house.gov',
title: 'Representative' },
{ name: 'Lloyd Doggett',
state: 'TX',
district: '35',
party: 'D',
twitter_account: 'RepLloydDoggett',
url: 'https://doggett.house.gov',
title: 'Representative' },
{ name: 'Mike Doyle',
state: 'PA',
district: '18',
party: 'D',
twitter_account: 'USRepMikeDoyle',
url: 'https://doyle.house.gov',
title: 'Representative' },
{ name: 'Sean Duffy',
state: 'WI',
district: '7',
party: 'R',
twitter_account: 'RepSeanDuffy',
url: 'https://duffy.house.gov',
title: 'Representative' },
{ name: 'Jeffrey Duncan',
state: 'SC',
district: '3',
party: 'R',
twitter_account: 'RepJeffDuncan',
url: 'https://jeffduncan.house.gov',
title: 'Representative' },
{ name: 'Neal Dunn',
state: 'FL',
district: '2',
party: 'R',
twitter_account: 'drnealdunnfl2',
url: 'https://dunn.house.gov',
title: 'Representative' },
{ name: 'Tom Emmer',
state: 'MN',
district: '6',
party: 'R',
twitter_account: 'RepTomEmmer',
url: 'https://emmer.house.gov',
title: 'Representative' },
{ name: 'Eliot Engel',
state: 'NY',
district: '16',
party: 'D',
twitter_account: 'RepEliotEngel',
url: 'https://engel.house.gov',
title: 'Representative' },
{ name: 'Veronica Escobar',
state: 'TX',
district: '16',
party: 'D',
twitter_account: 'RepEscobar',
url: 'https://escobar.house.gov/',
title: 'Representative' },
{ name: 'Anna Eshoo',
state: 'CA',
district: '18',
party: 'D',
twitter_account: 'RepAnnaEshoo',
url: 'http://eshoo.house.gov',
title: 'Representative' },
{ name: 'Adriano Espaillat',
state: 'NY',
district: '13',
party: 'D',
twitter_account: 'RepEspaillat',
url: 'https://espaillat.house.gov',
title: 'Representative' },
{ name: 'Ron Estes',
state: 'KS',
district: '4',
party: 'R',
twitter_account: 'RepRonEstes',
url: 'https://estes.house.gov',
title: 'Representative' },
{ name: 'Dwight Evans',
state: 'PA',
district: '3',
party: 'D',
twitter_account: 'RepDwightEvans',
url: 'https://evans.house.gov',
title: 'Representative' },
{ name: 'A. Ferguson',
state: 'GA',
district: '3',
party: 'R',
twitter_account: 'RepDrewFerguson',
url: 'https://ferguson.house.gov',
title: 'Representative' },
{ name: 'Abby Finkenauer',
state: 'IA',
district: '1',
party: 'D',
twitter_account: 'RepFinkenauer',
url: 'https://finkenauer.house.gov/',
title: 'Representative' },
{ name: 'Brian Fitzpatrick',
state: 'PA',
district: '1',
party: 'R',
twitter_account: 'repbrianfitz',
url: 'https://fitzpatrick.house.gov',
title: 'Representative' },
{ name: 'Chuck Fleischmann',
state: 'TN',
district: '3',
party: 'R',
twitter_account: 'RepChuck',
url: 'https://fleischmann.house.gov',
title: 'Representative' },
{ name: 'Lizzie Fletcher',
state: 'TX',
district: '7',
party: 'D',
twitter_account: 'RepFletcher',
url: 'https://fletcher.house.gov/',
title: 'Representative' },
{ name: 'Bill Flores',
state: 'TX',
district: '17',
party: 'R',
twitter_account: 'RepBillFlores',
url: 'https://flores.house.gov',
title: 'Representative' },
{ name: 'Jeff Fortenberry',
state: 'NE',
district: '1',
party: 'R',
twitter_account: 'JeffFortenberry',
url: 'https://fortenberry.house.gov',
title: 'Representative' },
{ name: 'Bill Foster',
state: 'IL',
district: '11',
party: 'D',
twitter_account: 'RepBillFoster',
url: 'https://foster.house.gov',
title: 'Representative' },
{ name: 'Virginia Foxx',
state: 'NC',
district: '5',
party: 'R',
twitter_account: 'VirginiaFoxx',
url: 'https://foxx.house.gov',
title: 'Representative' },
{ name: 'Lois Frankel',
state: 'FL',
district: '21',
party: 'D',
twitter_account: 'RepLoisFrankel',
url: 'https://frankel.house.gov',
title: 'Representative' },
{ name: 'Marcia Fudge',
state: 'OH',
district: '11',
party: 'D',
twitter_account: 'RepMarciaFudge',
url: 'https://fudge.house.gov',
title: 'Representative' },
{ name: 'Russ Fulcher',
state: 'ID',
district: '1',
party: 'R',
twitter_account: 'RepRussFulcher',
url: 'https://fulcher.house.gov/',
title: 'Representative' },
{ name: 'Tulsi Gabbard',
state: 'HI',
district: '2',
party: 'D',
twitter_account: 'TulsiPress',
url: 'https://gabbard.house.gov',
title: 'Representative' },
{ name: 'Matt Gaetz',
state: 'FL',
district: '1',
party: 'R',
twitter_account: 'RepMattGaetz',
url: 'https://gaetz.house.gov',
title: 'Representative' },
{ name: 'Mike Gallagher',
state: 'WI',
district: '8',
party: 'R',
twitter_account: 'RepGallagher',
url: 'https://gallagher.house.gov',
title: 'Representative' },
{ name: 'Ruben Gallego',
state: 'AZ',
district: '7',
party: 'D',
twitter_account: 'RepRubenGallego',
url: 'https://rubengallego.house.gov',
title: 'Representative' },
{ name: 'John Garamendi',
state: 'CA',
district: '3',
party: 'D',
twitter_account: 'RepGaramendi',
url: 'https://garamendi.house.gov',
title: 'Representative' },
{ name: 'Sylvia Garcia',
state: 'TX',
district: '29',
party: 'D',
twitter_account: 'RepSylviaGarcia',
url: 'https://sylviagarcia.house.gov/',
title: 'Representative' },
{ name: 'Jesús García',
state: 'IL',
district: '4',
party: 'D',
twitter_account: 'RepChuyGarcia',
url: 'https://chuygarcia.house.gov/',
title: 'Representative' },
{ name: 'Greg Gianforte',
state: 'MT',
district: 'At-Large',
party: 'R',
twitter_account: null,
url: 'https://gianforte.house.gov',
title: 'Representative' },
{ name: 'Bob Gibbs',
state: 'OH',
district: '7',
party: 'R',
twitter_account: 'RepBobGibbs',
url: 'https://gibbs.house.gov',
title: 'Representative' },
{ name: 'Louie Gohmert',
state: 'TX',
district: '1',
party: 'R',
twitter_account: 'RepLouieGohmert',
url: 'https://gohmert.house.gov',
title: 'Representative' },
{ name: 'Jared Golden',
state: 'ME',
district: '2',
party: 'D',
twitter_account: 'repgolden',
url: 'https://golden.house.gov',
title: 'Representative' },
{ name: 'Jimmy Gomez',
state: 'CA',
district: '34',
party: 'D',
twitter_account: 'RepJimmyGomez',
url: 'https://gomez.house.gov',
title: 'Representative' },
{ name: 'Anthony Gonzalez',
state: 'OH',
district: '16',
party: 'R',
twitter_account: 'RepAGonzalez',
url: 'https://anthonygonzalez.house.gov/',
title: 'Representative' },
{ name: 'Vicente Gonzalez',
state: 'TX',
district: '15',
party: 'D',
twitter_account: 'RepGonzalez',
url: 'https://gonzalez.house.gov',
title: 'Representative' },
{ name: 'Jenniffer González-Colón',
state: 'PR',
district: 'At-Large',
party: 'R',
twitter_account: 'repjenniffer',
url: 'https://gonzalez-colon.house.gov',
title: 'Resident Commissioner' },
{ name: 'Lance Gooden',
state: 'TX',
district: '5',
party: 'R',
twitter_account: 'RepLanceGooden',
url: 'https://gooden.house.gov/',
title: 'Representative' },
{ name: 'Paul Gosar',
state: 'AZ',
district: '4',
party: 'R',
twitter_account: 'RepGosar',
url: 'https://gosar.house.gov',
title: 'Representative' },
{ name: 'Josh Gottheimer',
state: 'NJ',
district: '5',
party: 'D',
twitter_account: 'RepJoshG',
url: 'https://gottheimer.house.gov',
title: 'Representative' },
{ name: 'Kay Granger',
state: 'TX',
district: '12',
party: 'R',
twitter_account: 'RepKayGranger',
url: 'https://kaygranger.house.gov',
title: 'Representative' },
{ name: 'Tom Graves',
state: 'GA',
district: '14',
party: 'R',
twitter_account: 'RepTomGraves',
url: 'https://tomgraves.house.gov',
title: 'Representative' },
{ name: 'Sam Graves',
state: 'MO',
district: '6',
party: 'R',
twitter_account: 'RepSamGraves',
url: 'https://graves.house.gov',
title: 'Representative' },
{ name: 'Garret Graves',
state: 'LA',
district: '6',
party: 'R',
twitter_account: 'RepGarretGraves',
url: 'https://garretgraves.house.gov',
title: 'Representative' },
{ name: 'Al Green',
state: 'TX',
district: '9',
party: 'D',
twitter_account: 'RepAlGreen',
url: 'https://algreen.house.gov',
title: 'Representative' },
{ name: 'Mark Green',
state: 'TN',
district: '7',
party: 'R',
twitter_account: 'RepMarkGreen',
url: 'https://markgreen.house.gov',
title: 'Representative' },
{ name: 'Morgan Griffith',
state: 'VA',
district: '9',
party: 'R',
twitter_account: 'RepMGriffith',
url: 'https://morgangriffith.house.gov',
title: 'Representative' },
{ name: 'Raúl Grijalva',
state: 'AZ',
district: '3',
party: 'D',
twitter_account: 'RepraulGrijalva',
url: 'https://grijalva.house.gov',
title: 'Representative' },
{ name: 'Glenn Grothman',
state: 'WI',
district: '6',
party: 'R',
twitter_account: 'RepGrothman',
url: 'https://grothman.house.gov',
title: 'Representative' },
{ name: 'Michael Guest',
state: 'MS',
district: '3',
party: 'R',
twitter_account: 'RepMichaelGuest',
url: 'https://guest.house.gov/',
title: 'Representative' },
{ name: 'Brett Guthrie',
state: 'KY',
district: '2',
party: 'R',
twitter_account: 'RepGuthrie',
url: 'https://guthrie.house.gov',
title: 'Representative' },
{ name: 'Debra Haaland',
state: 'NM',
district: '1',
party: 'D',
twitter_account: 'RepDebHaaland',
url: 'https://haaland.house.gov/',
title: 'Representative' },
{ name: 'Jim Hagedorn',
state: 'MN',
district: '1',
party: 'R',
twitter_account: 'RepHagedorn',
url: 'https://hagedorn.house.gov/',
title: 'Representative' },
{ name: 'Josh Harder',
state: 'CA',
district: '10',
party: 'D',
twitter_account: 'RepJoshHarder',
url: 'https://harder.house.gov/',
title: 'Representative' },
{ name: 'Andy Harris',
state: 'MD',
district: '1',
party: 'R',
twitter_account: 'RepAndyHarrisMD',
url: 'https://harris.house.gov',
title: 'Representative' },
{ name: 'Vicky Hartzler',
state: 'MO',
district: '4',
party: 'R',
twitter_account: 'RepHartzler',
url: 'https://hartzler.house.gov',
title: 'Representative' },
{ name: 'Alcee Hastings',
state: 'FL',
district: '20',
party: 'D',
twitter_account: 'RepHastingsFL',
url: 'https://alceehastings.house.gov',
title: 'Representative' },
{ name: 'Jahana Hayes',
state: 'CT',
district: '5',
party: 'D',
twitter_account: 'RepJahanaHayes',
url: 'https://hayes.house.gov/',
title: 'Representative' },
{ name: 'Denny Heck',
state: 'WA',
district: '10',
party: 'D',
twitter_account: 'RepDennyHeck',
url: 'https://dennyheck.house.gov',
title: 'Representative' },
{ name: 'Kevin Hern',
state: 'OK',
district: '1',
party: 'R',
twitter_account: 'repkevinhern',
url: 'https://hern.house.gov',
title: 'Representative' },
{ name: 'Jaime Herrera Beutler',
state: 'WA',
district: '3',
party: 'R',
twitter_account: 'HerreraBeutler',
url: 'https://herrerabeutler.house.gov',
title: 'Representative' },
{ name: 'Jody Hice',
state: 'GA',
district: '10',
party: 'R',
twitter_account: 'congressmanhice',
url: 'https://hice.house.gov',
title: 'Representative' },
{ name: 'Clay Higgins',
state: 'LA',
district: '3',
party: 'R',
twitter_account: 'RepClayHiggins',
url: 'https://clayhiggins.house.gov',
title: 'Representative' },
{ name: 'Brian Higgins',
state: 'NY',
district: '26',
party: 'D',
twitter_account: 'RepBrianHiggins',
url: 'https://higgins.house.gov',
title: 'Representative' },
{ name: 'French Hill',
state: 'AR',
district: '2',
party: 'R',
twitter_account: 'RepFrenchHill',
url: 'https://hill.house.gov',
title: 'Representative' },
{ name: 'Katie Hill',
state: 'CA',
district: '25',
party: 'D',
twitter_account: 'RepKatieHill',
url: 'https://katiehill.house.gov/',
title: 'Representative' },
{ name: 'Jim Himes',
state: 'CT',
district: '4',
party: 'D',
twitter_account: 'JAHimes',
url: 'https://himes.house.gov',
title: 'Representative' },
{ name: 'George Holding',
state: 'NC',
district: '2',
party: 'R',
twitter_account: 'RepHolding',
url: 'https://holding.house.gov',
title: 'Representative' },
{ name: 'Trey Hollingsworth',
state: 'IN',
district: '9',
party: 'R',
twitter_account: 'reptrey',
url: 'https://hollingsworth.house.gov',
title: 'Representative' },
{ name: 'Kendra Horn',
state: 'OK',
district: '5',
party: 'D',
twitter_account: 'RepKendraHorn',
url: 'https://horn.house.gov/',
title: 'Representative' },
{ name: 'Steven Horsford',
state: 'NV',
district: '4',
party: 'D',
twitter_account: 'RepHorsford',
url: 'http://horsford.house.gov',
title: 'Representative' },
{ name: 'Chrissy Houlahan',
state: 'PA',
district: '6',
party: 'D',
twitter_account: 'RepHoulahan',
url: 'https://houlahan.house.gov/',
title: 'Representative' },
{ name: 'Steny Hoyer',
state: 'MD',
district: '5',
party: 'D',
twitter_account: 'LeaderHoyer',
url: 'https://hoyer.house.gov',
title: 'Representative' },
{ name: 'Richard Hudson',
state: 'NC',
district: '8',
party: 'R',
twitter_account: 'RepRichHudson',
url: 'https://hudson.house.gov',
title: 'Representative' },
{ name: 'Jared Huffman',
state: 'CA',
district: '2',
party: 'D',
twitter_account: 'RepHuffman',
url: 'https://huffman.house.gov',
title: 'Representative' },
{ name: 'Bill Huizenga',
state: 'MI',
district: '2',
party: 'R',
twitter_account: 'RepHuizenga',
url: 'https://huizenga.house.gov',
title: 'Representative' },
{ name: 'Duncan Hunter',
state: 'CA',
district: '50',
party: 'R',
twitter_account: 'Rep_Hunter',
url: 'https://hunter.house.gov',
title: 'Representative' },
{ name: 'Will Hurd',
state: 'TX',
district: '23',
party: 'R',
twitter_account: 'hurdonthehill',
url: 'https://hurd.house.gov',
title: 'Representative' },
{ name: 'Sheila Jackson Lee',
state: 'TX',
district: '18',
party: 'D',
twitter_account: 'JacksonLeeTX18',
url: 'https://jacksonlee.house.gov',
title: 'Representative' },
{ name: 'Pramila Jayapal',
state: 'WA',
district: '7',
party: 'D',
twitter_account: 'RepJayapal',
url: 'https://jayapal.house.gov',
title: 'Representative' },
{ name: 'Hakeem Jeffries',
state: 'NY',
district: '8',
party: 'D',
twitter_account: 'RepJeffries',
url: 'https://jeffries.house.gov',
title: 'Representative' },
{ name: 'Eddie Johnson',
state: 'TX',
district: '30',
party: 'D',
twitter_account: 'RepEBJ',
url: 'https://ebjohnson.house.gov',
title: 'Representative' },
{ name: 'Bill Johnson',
state: 'OH',
district: '6',
party: 'R',
twitter_account: 'RepBillJohnson',
url: 'https://billjohnson.house.gov',
title: 'Representative' },
{ name: 'Hank Johnson',
state: 'GA',
district: '4',
party: 'D',
twitter_account: 'RepHankJohnson',
url: 'https://hankjohnson.house.gov',
title: 'Representative' },
{ name: 'Dusty Johnson',
state: 'SD',
district: 'At-Large',
party: 'R',
twitter_account: 'RepJohnson',
url: 'https://dustyjohnson.house.gov/',
title: 'Representative' },
{ name: 'Mike Johnson',
state: 'LA',
district: '4',
party: 'R',
twitter_account: 'RepMikeJohnson',
url: 'https://mikejohnson.house.gov',
title: 'Representative' },
{ name: 'Jim Jordan',
state: 'OH',
district: '4',
party: 'R',
twitter_account: 'Jim_Jordan',
url: 'https://jordan.house.gov',
title: 'Representative' },
{ name: 'John Joyce',
state: 'PA',
district: '13',
party: 'R',
twitter_account: 'RepJohnJoyce',
url: 'https://johnjoyce.house.gov/',
title: 'Representative' },
{ name: 'Dave Joyce',
state: 'OH',
district: '14',
party: 'R',
twitter_account: 'RepDaveJoyce',
url: 'https://joyce.house.gov',
title: 'Representative' },
{ name: 'Marcy Kaptur',
state: 'OH',
district: '9',
party: 'D',
twitter_account: 'RepMarcyKaptur',
url: 'https://kaptur.house.gov',
title: 'Representative' },
{ name: 'John Katko',
state: 'NY',
district: '24',
party: 'R',
twitter_account: 'RepJohnKatko',
url: 'https://katko.house.gov',
title: 'Representative' },
{ name: 'Bill Keating',
state: 'MA',
district: '9',
party: 'D',
twitter_account: 'USRepKeating',
url: 'https://keating.house.gov',
title: 'Representative' },
{ name: 'Fred Keller',
state: 'PA',
district: '12',
party: 'R',
twitter_account: 'RepFredKeller',
url: 'https://keller.house.gov/',
title: 'Representative' },
{ name: 'Robin Kelly',
state: 'IL',
district: '2',
party: 'D',
twitter_account: 'RepRobinKelly',
url: 'https://robinkelly.house.gov',
title: 'Representative' },
{ name: 'Mike Kelly',
state: 'PA',
district: '16',
party: 'R',
twitter_account: 'MikeKellyPA',
url: 'https://kelly.house.gov',
title: 'Representative' },
{ name: 'Trent Kelly',
state: 'MS',
district: '1',
party: 'R',
twitter_account: 'RepTrentKelly',
url: 'https://trentkelly.house.gov',
title: 'Representative' },
{ name: 'Joseph Kennedy',
state: 'MA',
district: '4',
party: 'D',
twitter_account: 'RepJoeKennedy',
url: 'https://kennedy.house.gov',
title: 'Representative' },
{ name: 'Ro Khanna',
state: 'CA',
district: '17',
party: 'D',
twitter_account: 'RepRoKhanna',
url: 'https://khanna.house.gov',
title: 'Representative' },
{ name: 'Dan Kildee',
state: 'MI',
district: '5',
party: 'D',
twitter_account: 'RepDanKildee',
url: 'https://dankildee.house.gov',
title: 'Representative' },
{ name: 'Derek Kilmer',
state: 'WA',
district: '6',
party: 'D',
twitter_account: 'RepDerekKilmer',
url: 'https://kilmer.house.gov',
title: 'Representative' },
{ name: 'Andy Kim',
state: 'NJ',
district: '3',
party: 'D',
twitter_account: 'RepAndyKimNJ',
url: 'https://kim.house.gov/',
title: 'Representative' },
{ name: 'Ron Kind',
state: 'WI',
district: '3',
party: 'D',
twitter_account: 'RepRonKind',
url: 'https://kind.house.gov',
title: 'Representative' },
{ name: 'Peter King',
state: 'NY',
district: '2',
party: 'R',
twitter_account: 'RepPeteKing',
url: 'https://peteking.house.gov',
title: 'Representative' },
{ name: 'Steve King',
state: 'IA',
district: '4',
party: 'R',
twitter_account: 'SteveKingIA',
url: 'https://steveking.house.gov',
title: 'Representative' },
{ name: 'Adam Kinzinger',
state: 'IL',
district: '16',
party: 'R',
twitter_account: 'RepKinzinger',
url: 'https://kinzinger.house.gov',
title: 'Representative' },
{ name: 'Ann Kirkpatrick',
state: 'AZ',
district: '2',
party: 'D',
twitter_account: 'RepKirkpatrick',
url: 'http://kirkpatrick.house.gov',
title: 'Representative' },
{ name: 'Raja Krishnamoorthi',
state: 'IL',
district: '8',
party: 'D',
twitter_account: 'congressmanraja',
url: 'https://krishnamoorthi.house.gov',
title: 'Representative' },
{ name: 'Ann Kuster',
state: 'NH',
district: '2',
party: 'D',
twitter_account: 'RepAnnieKuster',
url: 'https://kuster.house.gov',
title: 'Representative' },
{ name: 'David Kustoff',
state: 'TN',
district: '8',
party: 'R',
twitter_account: 'repdavidkustoff',
url: 'https://kustoff.house.gov',
title: 'Representative' },
{ name: 'Darin LaHood',
state: 'IL',
district: '18',
party: 'R',
twitter_account: 'RepLaHood',
url: 'https://lahood.house.gov',
title: 'Representative' },
{ name: 'Doug LaMalfa',
state: 'CA',
district: '1',
party: 'R',
twitter_account: 'RepLaMalfa',
url: 'https://lamalfa.house.gov',
title: 'Representative' },
{ name: 'Conor Lamb',
state: 'PA',
district: '17',
party: 'D',
twitter_account: 'RepConorLamb',
url: 'https://lamb.house.gov/',
title: 'Representative' },
{ name: 'Doug Lamborn',
state: 'CO',
district: '5',
party: 'R',
twitter_account: 'RepDLamborn',
url: 'https://lamborn.house.gov',
title: 'Representative' },
{ name: 'Jim Langevin',
state: 'RI',
district: '2',
party: 'D',
twitter_account: 'JimLangevin',
url: 'https://langevin.house.gov',
title: 'Representative' },
{ name: 'Rick Larsen',
state: 'WA',
district: '2',
party: 'D',
twitter_account: 'RepRickLarsen',
url: 'https://larsen.house.gov',
title: 'Representative' },
{ name: 'John Larson',
state: 'CT',
district: '1',
party: 'D',
twitter_account: 'RepJohnLarson',
url: 'https://larson.house.gov',
title: 'Representative' },
{ name: 'Robert Latta',
state: 'OH',
district: '5',
party: 'R',
twitter_account: 'BobLatta',
url: 'https://latta.house.gov',
title: 'Representative' },
{ name: 'Brenda Lawrence',
state: 'MI',
district: '14',
party: 'D',
twitter_account: 'RepLawrence',
url: 'https://lawrence.house.gov',
title: 'Representative' },
{ name: 'Al Lawson',
state: 'FL',
district: '5',
party: 'D',
twitter_account: 'RepAlLawsonJr',
url: 'https://lawson.house.gov',
title: 'Representative' },
{ name: 'Barbara Lee',
state: 'CA',
district: '13',
party: 'D',
twitter_account: 'RepBarbaraLee',
url: 'https://lee.house.gov',
title: 'Representative' },
{ name: 'Susie Lee',
state: 'NV',
district: '3',
party: 'D',
twitter_account: 'RepSusieLee',
url: 'https://susielee.house.gov/',
title: 'Representative' },
{ name: 'Debbie Lesko',
state: 'AZ',
district: '8',
party: 'R',
twitter_account: 'RepDLesko',
url: 'https://lesko.house.gov/',
title: 'Representative' },
{ name: 'Andy Levin',
state: 'MI',
district: '9',
party: 'D',
twitter_account: 'RepAndyLevin',
url: 'https://andylevin.house.gov/',
title: 'Representative' },
{ name: 'Mike Levin',
state: 'CA',
district: '49',
party: 'D',
twitter_account: 'RepMikeLevin',
url: 'https://mikelevin.house.gov/',
title: 'Representative' },
{ name: 'John Lewis',
state: 'GA',
district: '5',
party: 'D',
twitter_account: 'RepJohnLewis',
url: 'https://johnlewis.house.gov',
title: 'Representative' },
{ name: 'Ted Lieu',
state: 'CA',
district: '33',
party: 'D',
twitter_account: 'RepTedLieu',
url: 'https://lieu.house.gov',
title: 'Representative' },
{ name: 'Daniel Lipinski',
state: 'IL',
district: '3',
party: 'D',
twitter_account: 'RepLipinski',
url: 'https://lipinski.house.gov',
title: 'Representative' },
{ name: 'Dave Loebsack',
state: 'IA',
district: '2',
party: 'D',
twitter_account: 'DaveLoebsack',
url: 'https://loebsack.house.gov',
title: 'Representative' },
{ name: 'Zoe Lofgren',
state: 'CA',
district: '19',
party: 'D',
twitter_account: 'RepZoeLofgren',
url: 'https://lofgren.house.gov',
title: 'Representative' },
{ name: 'Billy Long',
state: 'MO',
district: '7',
party: 'R',
twitter_account: 'USRepLong',
url: 'https://long.house.gov',
title: 'Representative' },
{ name: 'Barry Loudermilk',
state: 'GA',
district: '11',
party: 'R',
twitter_account: 'RepLoudermilk',
url: 'https://loudermilk.house.gov',
title: 'Representative' },
{ name: 'Alan Lowenthal',
state: 'CA',
district: '47',
party: 'D',
twitter_account: 'RepLowenthal',
url: 'https://lowenthal.house.gov',
title: 'Representative' },
{ name: 'Nita Lowey',
state: 'NY',
district: '17',
party: 'D',
twitter_account: 'NitaLowey',
url: 'https://lowey.house.gov',
title: 'Representative' },
{ name: 'Frank Lucas',
state: 'OK',
district: '3',
party: 'R',
twitter_account: 'RepFrankLucas',
url: 'https://lucas.house.gov',
title: 'Representative' },
{ name: 'Blaine Luetkemeyer',
state: 'MO',
district: '3',
party: 'R',
twitter_account: 'RepBlaine',
url: 'https://luetkemeyer.house.gov',
title: 'Representative' },
{ name: 'Ben Luján',
state: 'NM',
district: '3',
party: 'D',
twitter_account: 'RepBenRayLujan',
url: 'https://lujan.house.gov',
title: 'Representative' },
{ name: 'Elaine Luria',
state: 'VA',
district: '2',
party: 'D',
twitter_account: 'RepElaineLuria',
url: 'https://luria.house.gov/',
title: 'Representative' },
{ name: 'Stephen Lynch',
state: 'MA',
district: '8',
party: 'D',
twitter_account: 'RepStephenLynch',
url: 'https://lynch.house.gov',
title: 'Representative' },
{ name: 'Tom Malinowski',
state: 'NJ',
district: '7',
party: 'D',
twitter_account: 'RepMalinowski',
url: 'https://malinowski.house.gov/',
title: 'Representative' },
{ name: 'Sean Maloney',
state: 'NY',
district: '18',
party: 'D',
twitter_account: 'RepSeanMaloney',
url: 'https://seanmaloney.house.gov',
title: 'Representative' },
{ name: 'Carolyn Maloney',
state: 'NY',
district: '12',
party: 'D',
twitter_account: 'RepMaloney',
url: 'https://maloney.house.gov',
title: 'Representative' },
{ name: 'Kenny Marchant',
state: 'TX',
district: '24',
party: 'R',
twitter_account: 'RepKenMarchant',
url: 'https://marchant.house.gov',
title: 'Representative' },
{ name: 'Tom Marino',
state: 'PA',
district: '12',
party: 'R',
twitter_account: 'RepTomMarino',
url: 'https://marino.house.gov',
title: 'Representative' },
{ name: 'Roger Marshall',
state: 'KS',
district: '1',
party: 'R',
twitter_account: 'RepMarshall',
url: 'https://marshall.house.gov',
title: 'Representative' },
{ name: 'Thomas Massie',
state: 'KY',
district: '4',
party: 'R',
twitter_account: 'RepThomasMassie',
url: 'https://massie.house.gov',
title: 'Representative' },
{ name: 'Brian Mast',
state: 'FL',
district: '18',
party: 'R',
twitter_account: 'repbrianmast',
url: 'https://mast.house.gov',
title: 'Representative' },
{ name: 'Doris Matsui',
state: 'CA',
district: '6',
party: 'D',
twitter_account: 'DorisMatsui',
url: 'http://matsui.house.gov',
title: 'Representative' },
{ name: 'Ben McAdams',
state: 'UT',
district: '4',
party: 'D',
twitter_account: 'RepBenMcAdams',
url: 'https://mcadams.house.gov/',
title: 'Representative' },
{ name: 'Lucy McBath',
state: 'GA',
district: '6',
party: 'D',
twitter_account: 'replucymcbath',
url: 'https://mcbath.house.gov/',
title: 'Representative' },
{ name: 'Kevin McCarthy',
state: 'CA',
district: '23',
party: 'R',
twitter_account: 'GOPLeader',
url: 'https://kevinmccarthy.house.gov',
title: 'Representative' },
{ name: 'Michael McCaul',
state: 'TX',
district: '10',
party: 'R',
twitter_account: 'RepMcCaul',
url: 'https://mccaul.house.gov',
title: 'Representative' },
{ name: 'Tom McClintock',
state: 'CA',
district: '4',
party: 'R',
twitter_account: 'RepMcClintock',
url: 'https://mcclintock.house.gov',
title: 'Representative' },
{ name: 'Betty McCollum',
state: 'MN',
district: '4',
party: 'D',
twitter_account: 'BettyMcCollum04',
url: 'https://mccollum.house.gov',
title: 'Representative' },
{ name: 'A. McEachin',
state: 'VA',
district: '4',
party: 'D',
twitter_account: 'RepMcEachin',
url: 'https://mceachin.house.gov',
title: 'Representative' },
{ name: 'Jim McGovern',
state: 'MA',
district: '2',
party: 'D',
twitter_account: 'RepMcGovern',
url: 'https://mcgovern.house.gov',
title: 'Representative' },
{ name: 'Patrick McHenry',
state: 'NC',
district: '10',
party: 'R',
twitter_account: 'PatrickMcHenry',
url: 'https://mchenry.house.gov',
title: 'Representative' },
{ name: 'David McKinley',
state: 'WV',
district: '1',
party: 'R',
twitter_account: 'RepMcKinley',
url: 'https://mckinley.house.gov',
title: 'Representative' },
{ name: 'Cathy McMorris Rodgers',
state: 'WA',
district: '5',
party: 'R',
twitter_account: 'CathyMcMorris',
url: 'https://mcmorris.house.gov',
title: 'Representative' },
{ name: 'Jerry McNerney',
state: 'CA',
district: '9',
party: 'D',
twitter_account: 'RepMcNerney',
url: 'https://mcnerney.house.gov',
title: 'Representative' },
{ name: 'Mark Meadows',
state: 'NC',
district: '11',
party: 'R',
twitter_account: 'RepMarkMeadows',
url: 'https://meadows.house.gov',
title: 'Representative' },
{ name: 'Gregory Meeks',
state: 'NY',
district: '5',
party: 'D',
twitter_account: 'RepGregoryMeeks',
url: 'https://meeks.house.gov',
title: 'Representative' },
{ name: 'Grace Meng',
state: 'NY',
district: '6',
party: 'D',
twitter_account: 'RepGraceMeng',
url: 'https://meng.house.gov',
title: 'Representative' },
{ name: 'Daniel Meuser',
state: 'PA',
district: '9',
party: 'R',
twitter_account: 'RepMeuser',
url: 'https://meuser.house.gov/',
title: 'Representative' },
{ name: 'Carol Miller',
state: 'WV',
district: '3',
party: 'R',
twitter_account: 'RepCarolMiller',
url: 'https://miller.house.gov/',
title: 'Representative' },
{ name: 'Paul Mitchell',
state: 'MI',
district: '10',
party: 'R',
twitter_account: 'RepPaulMitchell',
url: 'https://mitchell.house.gov',
title: 'Representative' },
{ name: 'John Moolenaar',
state: 'MI',
district: '4',
party: 'R',
twitter_account: 'RepMoolenaar',
url: 'https://moolenaar.house.gov',
title: 'Representative' },
{ name: 'Alex Mooney',
state: 'WV',
district: '2',
party: 'R',
twitter_account: 'RepAlexMooney',
url: 'https://mooney.house.gov',
title: 'Representative' },
{ name: 'Gwen Moore',
state: 'WI',
district: '4',
party: 'D',
twitter_account: 'RepGwenMoore',
url: 'https://gwenmoore.house.gov',
title: 'Representative' },
{ name: 'Joe Morelle',
state: 'NY',
district: '25',
party: 'D',
twitter_account: 'repjoemorelle',
url: 'https://morelle.house.gov',
title: 'Representative' },
{ name: 'Seth Moulton',
state: 'MA',
district: '6',
party: 'D',
twitter_account: 'teammoulton',
url: 'https://moulton.house.gov',
title: 'Representative' },
{ name: 'Debbie Mucarsel-Powell',
state: 'FL',
district: '26',
party: 'D',
twitter_account: 'RepDMP',
url: 'https://mucarsel-powell.house.gov/',
title: 'Representative' },
{ name: 'Markwayne Mullin',
state: 'OK',
district: '2',
party: 'R',
twitter_account: 'RepMullin',
url: 'https://mullin.house.gov',
title: 'Representative' },
{ name: 'Stephanie Murphy',
state: 'FL',
district: '7',
party: 'D',
twitter_account: 'RepStephMurphy',
url: 'https://stephaniemurphy.house.gov',
title: 'Representative' },
{ name: 'Greg Murphy',
state: 'NC',
district: '3',
party: 'R',
twitter_account: 'RepGregMurphy',
url: 'https://gregmurphy.house.gov/',
title: 'Representative' },
{ name: 'Jerrold Nadler',
state: 'NY',
district: '10',
party: 'D',
twitter_account: 'RepJerryNadler',
url: 'https://nadler.house.gov',
title: 'Representative' },
{ name: 'Grace Napolitano',
state: 'CA',
district: '32',
party: 'D',
twitter_account: 'GraceNapolitano',
url: 'https://napolitano.house.gov',
title: 'Representative' },
{ name: 'Richard Neal',
state: 'MA',
district: '1',
party: 'D',
twitter_account: 'RepRichardNeal',
url: 'https://neal.house.gov',
title: 'Representative' },
{ name: 'Joe Neguse',
state: 'CO',
district: '2',
party: 'D',
twitter_account: 'RepJoeNeguse',
url: 'https://neguse.house.gov/',
title: 'Representative' },
{ name: 'Dan Newhouse',
state: 'WA',
district: '4',
party: 'R',
twitter_account: 'RepNewhouse',
url: 'https://newhouse.house.gov',
title: 'Representative' },
{ name: 'Donald Norcross',
state: 'NJ',
district: '1',
party: 'D',
twitter_account: 'DonaldNorcross',
url: 'https://norcross.house.gov',
title: 'Representative' },
{ name: 'Ralph Norman',
state: 'SC',
district: '5',
party: 'R',
twitter_account: 'RepRalphNorman',
url: 'https://norman.house.gov',
title: 'Representative' },
{ name: 'Eleanor Norton',
state: 'DC',
district: 'At-Large',
party: 'D',
twitter_account: 'EleanorNorton',
url: 'https://norton.house.gov',
title: 'Delegate' },
{ name: 'Devin Nunes',
state: 'CA',
district: '22',
party: 'R',
twitter_account: 'RepDevinNunes',
url: 'https://nunes.house.gov',
title: 'Representative' },
{ name: 'Tom O\'Halleran',
state: 'AZ',
district: '1',
party: 'D',
twitter_account: 'repohalleran',
url: 'https://ohalleran.house.gov',
title: 'Representative' },
{ name: 'Alexandria Ocasio-Cortez',
state: 'NY',
district: '14',
party: 'D',
twitter_account: 'RepAOC',
url: 'https://ocasio-cortez.house.gov/',
title: 'Representative' } ,
{ name: 'Ilhan Omar',
state: 'MN',
district: '5',
party: 'D',
twitter_account: 'Ilhan',
url: 'https://omar.house.gov/',
title: 'Representative' },
{ name: 'Steven Palazzo',
state: 'MS',
district: '4',
party: 'R',
twitter_account: 'CongPalazzo',
url: 'https://palazzo.house.gov',
title: 'Representative' },
{ name: 'Frank Pallone',
state: 'NJ',
district: '6',
party: 'D',
twitter_account: 'FrankPallone',
url: 'https://pallone.house.gov',
title: 'Representative' },
{ name: 'Gary Palmer',
state: 'AL',
district: '6',
party: 'R',
twitter_account: 'USRepGaryPalmer',
url: 'https://palmer.house.gov',
title: 'Representative' },
{ name: 'Jimmy Panetta',
state: 'CA',
district: '20',
party: 'D',
twitter_account: 'RepJimmyPanetta',
url: 'https://panetta.house.gov',
title: 'Representative' },
{ name: 'Chris Pappas',
state: 'NH',
district: '1',
party: 'D',
twitter_account: 'RepChrisPappas',
url: 'https://pappas.house.gov/',
title: 'Representative' },
{ name: 'Bill Pascrell',
state: 'NJ',
district: '9',
party: 'D',
twitter_account: 'BillPascrell',
url: 'https://pascrell.house.gov',
title: 'Representative' },
{ name: 'Donald Payne',
state: 'NJ',
district: '10',
party: 'D',
twitter_account: 'RepDonaldPayne',
url: 'https://payne.house.gov',
title: 'Representative' },
{ name: 'Nancy Pelosi',
state: 'CA',
district: '12',
party: 'D',
twitter_account: 'SpeakerPelosi',
url: 'https://pelosi.house.gov',
title: 'Representative' },
{ name: 'Greg Pence',
state: 'IN',
district: '6',
party: 'R',
twitter_account: 'RepGregPence',
url: 'https://pence.house.gov/',
title: 'Representative' },
{ name: 'Ed Perlmutter',
state: 'CO',
district: '7',
party: 'D',
twitter_account: 'RepPerlmutter',
url: 'https://perlmutter.house.gov',
title: 'Representative' },
{ name: 'Scott Perry',
state: 'PA',
district: '10',
party: 'R',
twitter_account: 'RepScottPerry',
url: 'https://perry.house.gov',
title: 'Representative' },
{ name: 'Scott Peters',
state: 'CA',
district: '52',
party: 'D',
twitter_account: 'RepScottPeters',
url: 'https://scottpeters.house.gov',
title: 'Representative' },
{ name: 'Collin Peterson',
state: 'MN',
district: '7',
party: 'D',
twitter_account: null,
url: 'https://collinpeterson.house.gov',
title: 'Representative' },
{ name: 'Dean Phillips',
state: 'MN',
district: '3',
party: 'D',
twitter_account: 'RepDeanPhillips',
url: 'https://phillips.house.gov/',
title: 'Representative' },
{ name: 'Chellie Pingree',
state: 'ME',
district: '1',
party: 'D',
twitter_account: 'ChelliePingree',
url: 'https://pingree.house.gov',
title: 'Representative' },
{ name: 'Stacey Plaskett',
state: 'VI',
district: 'At-Large',
party: 'D',
twitter_account: 'staceyplaskett',
url: 'https://plaskett.house.gov',
title: 'Delegate' },
{ name: 'Mark Pocan',
state: 'WI',
district: '2',
party: 'D',
twitter_account: 'RepMarkPocan',
url: 'https://pocan.house.gov',
title: 'Representative' },
{ name: 'Katie Porter',
state: 'CA',
district: '45',
party: 'D',
twitter_account: 'RepKatiePorter',
url: 'https://porter.house.gov/',
title: 'Representative' },
{ name: 'Bill Posey',
state: 'FL',
district: '8',
party: 'R',
twitter_account: 'CongBillPosey',
url: 'https://posey.house.gov',
title: 'Representative' },
{ name: 'Ayanna Pressley',
state: 'MA',
district: '7',
party: 'D',
twitter_account: 'RepPressley',
url: 'https://pressley.house.gov/',
title: 'Representative' },
{ name: 'David Price',
state: 'NC',
district: '4',
party: 'D',
twitter_account: 'RepDavidEPrice',
url: 'https://price.house.gov',
title: 'Representative' },
{ name: 'Mike Quigley',
state: 'IL',
district: '5',
party: 'D',
twitter_account: 'RepMikeQuigley',
url: 'https://quigley.house.gov',
title: 'Representative' },
{ name: 'Amata Radewagen',
state: 'AS',
district: 'At-Large',
party: 'R',
twitter_account: 'RepAmata',
url: 'https://radewagen.house.gov',
title: 'Delegate' },
{ name: 'Jamie Raskin',
state: 'MD',
district: '8',
party: 'D',
twitter_account: 'repraskin',
url: 'https://raskin.house.gov',
title: 'Representative' },
{ name: 'John Ratcliffe',
state: 'TX',
district: '4',
party: 'R',
twitter_account: 'RepRatcliffe',
url: 'https://ratcliffe.house.gov',
title: 'Representative' },
{ name: 'Tom Reed',
state: 'NY',
district: '23',
party: 'R',
twitter_account: 'RepTomReed',
url: 'https://reed.house.gov',
title: 'Representative' },
{ name: 'Guy Reschenthaler',
state: 'PA',
district: '14',
party: 'R',
twitter_account: 'GReschenthaler',
url: 'https://reschenthaler.house.gov/',
title: 'Representative' },
{ name: 'Kathleen Rice',
state: 'NY',
district: '4',
party: 'D',
twitter_account: 'RepKathleenRice',
url: 'https://kathleenrice.house.gov',
title: 'Representative' },
{ name: 'Tom Rice',
state: 'SC',
district: '7',
party: 'R',
twitter_account: 'RepTomRice',
url: 'https://rice.house.gov',
title: 'Representative' },
{ name: 'Cedric Richmond',
state: 'LA',
district: '2',
party: 'D',
twitter_account: 'RepRichmond',
url: 'https://richmond.house.gov',
title: 'Representative' },
{ name: 'Denver Riggleman',
state: 'VA',
district: '5',
party: 'R',
twitter_account: 'RepRiggleman',
url: 'https://riggleman.house.gov/',
title: 'Representative' },
{ name: 'Martha Roby',
state: 'AL',
district: '2',
party: 'R',
twitter_account: 'RepMarthaRoby',
url: 'https://roby.house.gov',
title: 'Representative' },
{ name: 'Phil Roe',
state: 'TN',
district: '1',
party: 'R',
twitter_account: 'DrPhilRoe',
url: 'https://roe.house.gov',
title: 'Representative' },
{ name: 'Harold Rogers',
state: 'KY',
district: '5',
party: 'R',
twitter_account: 'RepHalRogers',
url: 'https://halrogers.house.gov',
title: 'Representative' },
{ name: 'Mike Rogers',
state: 'AL',
district: '3',
party: 'R',
twitter_account: 'RepMikeRogersAL',
url: 'https://mikerogers.house.gov',
title: 'Representative' },
{ name: 'Francis Rooney',
state: 'FL',
district: '19',
party: 'R',
twitter_account: 'RepRooney',
url: 'https://francisrooney.house.gov',
title: 'Representative' },
{ name: 'John Rose',
state: 'TN',
district: '6',
party: 'R',
twitter_account: 'RepJohnRose',
url: 'https://johnrose.house.gov/',
title: 'Representative' },
{ name: 'Max Rose',
state: 'NY',
district: '11',
party: 'D',
twitter_account: 'RepMaxRose',
url: 'https://maxrose.house.gov/',
title: 'Representative' },
{ name: 'Harley Rouda',
state: 'CA',
district: '48',
party: 'D',
twitter_account: 'RepHarley',
url: 'https://rouda.house.gov/',
title: 'Representative' },
{ name: 'David Rouzer',
state: 'NC',
district: '7',
party: 'R',
twitter_account: 'RepDavidRouzer',
url: 'https://rouzer.house.gov',
title: 'Representative' },
{ name: 'Chip Roy',
state: 'TX',
district: '21',
party: 'R',
twitter_account: 'RepChipRoy',
url: 'https://roy.house.gov/',
title: 'Representative' },
{ name: 'Lucille Roybal-Allard',
state: 'CA',
district: '40',
party: 'D',
twitter_account: 'RepRoybalAllard',
url: 'https://roybal-allard.house.gov',
title: 'Representative' },
{ name: 'Raul Ruiz',
state: 'CA',
district: '36',
party: 'D',
twitter_account: 'CongressmanRuiz',
url: 'https://ruiz.house.gov',
title: 'Representative' },
{ name: 'C.A. Dutch Ruppersberger',
state: 'MD',
district: '2',
party: 'D',
twitter_account: 'Call_Me_Dutch',
url: 'https://ruppersberger.house.gov',
title: 'Representative' },
{ name: 'Bobby Rush',
state: 'IL',
district: '1',
party: 'D',
twitter_account: 'RepBobbyRush',
url: 'https://rush.house.gov',
title: 'Representative' },
{ name: 'John Rutherford',
state: 'FL',
district: '4',
party: 'R',
twitter_account: 'RepRutherfordFL',
url: 'https://rutherford.house.gov',
title: 'Representative' },
{ name: 'Tim Ryan',
state: 'OH',
district: '13',
party: 'D',
twitter_account: 'RepTimRyan',
url: 'https://timryan.house.gov',
title: 'Representative' },
{ name: 'Gregorio Sablan',
state: 'MP',
district: 'At-Large',
party: 'D',
twitter_account: 'Kilili_Sablan',
url: 'https://sablan.house.gov',
title: 'Delegate' },
{ name: 'Michael San Nicolas',
state: 'GU',
district: 'At-Large',
party: 'D',
twitter_account: 'GuamCongressman',
url: 'https://sannicolas.house.gov/',
title: 'Delegate' },
{ name: 'Linda Sánchez',
state: 'CA',
district: '38',
party: 'D',
twitter_account: 'RepLindaSanchez',
url: 'https://lindasanchez.house.gov',
title: 'Representative' },
{ name: 'John Sarbanes',
state: 'MD',
district: '3',
party: 'D',
twitter_account: 'RepSarbanes',
url: 'https://sarbanes.house.gov',
title: 'Representative' },
{ name: 'Steve Scalise',
state: 'LA',
district: '1',
party: 'R',
twitter_account: 'SteveScalise',
url: 'https://scalise.house.gov',
title: 'Representative' },
{ name: 'Mary Scanlon',
state: 'PA',
district: '5',
party: 'D',
twitter_account: 'RepMGS',
url: 'https://scanlon.house.gov',
title: 'Representative' },
{ name: 'Jan Schakowsky',
state: 'IL',
district: '9',
party: 'D',
twitter_account: 'JanSchakowsky',
url: 'https://schakowsky.house.gov',
title: 'Representative' },
{ name: 'Adam Schiff',
state: 'CA',
district: '28',
party: 'D',
twitter_account: 'RepAdamSchiff',
url: 'https://schiff.house.gov',
title: 'Representative' },
{ name: 'Brad Schneider',
state: 'IL',
district: '10',
party: 'D',
twitter_account: 'repschneider',
url: 'https://schneider.house.gov',
title: 'Representative' },
{ name: 'Kurt Schrader',
state: 'OR',
district: '5',
party: 'D',
twitter_account: 'RepSchrader',
url: 'https://schrader.house.gov',
title: 'Representative' },
{ name: 'Kim Schrier',
state: 'WA',
district: '8',
party: 'D',
twitter_account: 'RepKimSchrier',
url: 'https://schrier.house.gov/',
title: 'Representative' },
{ name: 'David Schweikert',
state: 'AZ',
district: '6',
party: 'R',
twitter_account: 'RepDavid',
url: 'https://schweikert.house.gov',
title: 'Representative' },
{ name: 'Austin Scott',
state: 'GA',
district: '8',
party: 'R',
twitter_account: 'AustinScottGA08',
url: 'https://austinscott.house.gov',
title: 'Representative' },
{ name: 'Robert Scott',
state: 'VA',
district: '3',
party: 'D',
twitter_account: 'BobbyScott',
url: 'https://bobbyscott.house.gov',
title: 'Representative' },
{ name: 'David Scott',
state: 'GA',
district: '13',
party: 'D',
twitter_account: 'RepDavidScott',
url: 'https://davidscott.house.gov',
title: 'Representative' },
{ name: 'F. Sensenbrenner',
state: 'WI',
district: '5',
party: 'R',
twitter_account: 'JimPressOffice',
url: 'https://sensenbrenner.house.gov',
title: 'Representative' },
{ name: 'José Serrano',
state: 'NY',
district: '15',
party: 'D',
twitter_account: 'RepJoseSerrano',
url: 'https://serrano.house.gov',
title: 'Representative' },
{ name: 'Terri Sewell',
state: 'AL',
district: '7',
party: 'D',
twitter_account: 'RepTerriSewell',
url: 'https://sewell.house.gov',
title: 'Representative' },
{ name: 'Donna Shalala',
state: 'FL',
district: '27',
party: 'D',
twitter_account: 'RepShalala',
url: 'https://shalala.house.gov/',
title: 'Representative' },
{ name: 'Brad Sherman',
state: 'CA',
district: '30',
party: 'D',
twitter_account: 'BradSherman',
url: 'https://sherman.house.gov',
title: 'Representative' },
{ name: 'Mikie Sherrill',
state: 'NJ',
district: '11',
party: 'D',
twitter_account: 'RepSherrill',
url: 'https://sherrill.house.gov/',
title: 'Representative' },
{ name: 'John Shimkus',
state: 'IL',
district: '15',
party: 'R',
twitter_account: 'RepShimkus',
url: 'https://shimkus.house.gov',
title: 'Representative' },
{ name: 'Mike Simpson',
state: 'ID',
district: '2',
party: 'R',
twitter_account: 'CongMikeSimpson',
url: 'https://simpson.house.gov',
title: 'Representative' },
{ name: 'Albio Sires',
state: 'NJ',
district: '8',
party: 'D',
twitter_account: 'RepSires',
url: 'https://sires.house.gov',
title: 'Representative' },
{ name: 'Elissa Slotkin',
state: 'MI',
district: '8',
party: 'D',
twitter_account: 'RepSlotkin',
url: 'https://slotkin.house.gov/',
title: 'Representative' },
{ name: 'Christopher Smith',
state: 'NJ',
district: '4',
party: 'R',
twitter_account: 'RepChrisSmith',
url: 'https://chrissmith.house.gov',
title: 'Representative' },
{ name: 'Adam Smith',
state: 'WA',
district: '9',
party: 'D',
twitter_account: 'RepAdamSmith',
url: 'https://adamsmith.house.gov',
title: 'Representative' },
{ name: 'Adrian Smith',
state: 'NE',
district: '3',
party: 'R',
twitter_account: 'RepAdrianSmith',
url: 'https://adriansmith.house.gov',
title: 'Representative' },
{ name: 'Jason Smith',
state: 'MO',
district: '8',
party: 'R',
twitter_account: 'RepJasonSmith',
url: 'https://jasonsmith.house.gov',
title: 'Representative' },
{ name: 'Lloyd Smucker',
state: 'PA',
district: '11',
party: 'R',
twitter_account: 'RepSmucker',
url: 'https://smucker.house.gov',
title: 'Representative' },
{ name: 'Darren Soto',
state: 'FL',
district: '9',
party: 'D',
twitter_account: 'RepDarrenSoto',
url: 'https://soto.house.gov',
title: 'Representative' },
{ name: 'Abigail Spanberger',
state: 'VA',
district: '7',
party: 'D',
twitter_account: 'RepSpanberger',
url: 'https://spanberger.house.gov/',
title: 'Representative' },
{ name: 'Ross Spano',
state: 'FL',
district: '15',
party: 'R',
twitter_account: 'RepRossSpano',
url: 'https://spano.house.gov/',
title: 'Representative' },
{ name: 'Jackie Speier',
state: 'CA',
district: '14',
party: 'D',
twitter_account: 'RepSpeier',
url: 'https://speier.house.gov',
title: 'Representative' },
{ name: 'Greg Stanton',
state: 'AZ',
district: '9',
party: 'D',
twitter_account: 'RepGregStanton',
url: 'https://stanton.house.gov/',
title: 'Representative' },
{ name: 'Pete Stauber',
state: 'MN',
district: '8',
party: 'R',
twitter_account: 'RepPeteStauber',
url: 'https://stauber.house.gov/',
title: 'Representative' },
{ name: 'Elise Stefanik',
state: 'NY',
district: '21',
party: 'R',
twitter_account: 'RepStefanik',
url: 'https://stefanik.house.gov',
title: 'Representative' },
{ name: 'Bryan Steil',
state: 'WI',
district: '1',
party: 'R',
twitter_account: 'RepBryanSteil',
url: 'https://steil.house.gov/',
title: 'Representative' },
{ name: 'Greg Steube',
state: 'FL',
district: '17',
party: 'R',
twitter_account: 'RepGregSteube',
url: 'https://steube.house.gov/',
title: 'Representative' },
{ name: 'Haley Stevens',
state: 'MI',
district: '11',
party: 'D',
twitter_account: 'RepHaleyStevens',
url: 'https://stevens.house.gov/',
title: 'Representative' },
{ name: 'Chris Stewart',
state: 'UT',
district: '2',
party: 'R',
twitter_account: 'RepChrisStewart',
url: 'https://stewart.house.gov',
title: 'Representative' },
{ name: 'Steve Stivers',
state: 'OH',
district: '15',
party: 'R',
twitter_account: 'RepSteveStivers',
url: 'https://stivers.house.gov',
title: 'Representative' },
{ name: 'Thomas Suozzi',
state: 'NY',
district: '3',
party: 'D',
twitter_account: 'RepTomSuozzi',
url: 'https://suozzi.house.gov',
title: 'Representative' },
{ name: 'Eric Swalwell',
state: 'CA',
district: '15',
party: 'D',
twitter_account: 'RepSwalwell',
url: 'https://swalwell.house.gov',
title: 'Representative' },
{ name: 'Mark Takano',
state: 'CA',
district: '41',
party: 'D',
twitter_account: 'RepMarkTakano',
url: 'https://takano.house.gov',
title: 'Representative' },
{ name: 'Van Taylor',
state: 'TX',
district: '3',
party: 'R',
twitter_account: 'RepVanTaylor',
url: 'https://vantaylor.house.gov/',
title: 'Representative' },
{ name: 'Glenn Thompson',
state: 'PA',
district: '15',
party: 'R',
twitter_account: 'CongressmanGT',
url: 'https://thompson.house.gov',
title: 'Representative' },
{ name: 'Mike Thompson',
state: 'CA',
district: '5',
party: 'D',
twitter_account: 'RepThompson',
url: 'https://mikethompson.house.gov',
title: 'Representative' },
{ name: 'Bennie Thompson',
state: 'MS',
district: '2',
party: 'D',
twitter_account: 'BennieGThompson',
url: 'https://benniethompson.house.gov',
title: 'Representative' },
{ name: 'William Thornberry',
state: 'TX',
district: '13',
party: 'R',
twitter_account: 'MacTXPress',
url: 'https://thornberry.house.gov',
title: 'Representative' },
{ name: 'William Timmons',
state: 'SC',
district: '4',
party: 'R',
twitter_account: 'RepTimmons',
url: 'https://timmons.house.gov/',
title: 'Representative' },
{ name: 'Dina Titus',
state: 'NV',
district: '1',
party: 'D',
twitter_account: 'RepDinaTitus',
url: 'https://titus.house.gov',
title: 'Representative' },
{ name: 'Rashida Tlaib',
state: 'MI',
district: '13',
party: 'D',
twitter_account: 'RepRashida',
url: 'https://tlaib.house.gov/',
title: 'Representative' },
{ name: 'Paul Tonko',
state: 'NY',
district: '20',
party: 'D',
twitter_account: 'RepPaulTonko',
url: 'https://tonko.house.gov',
title: 'Representative' },
{ name: 'Norma Torres',
state: 'CA',
district: '35',
party: 'D',
twitter_account: 'NormaJTorres',
url: 'https://torres.house.gov',
title: 'Representative' },
{ name: 'Xochitl Torres Small',
state: 'NM',
district: '2',
party: 'D',
twitter_account: 'RepTorresSmall',
url: 'http://torressmall.house.gov',
title: 'Representative' },
{ name: 'Lori Trahan',
state: 'MA',
district: '3',
party: 'D',
twitter_account: 'RepLoriTrahan',
url: 'https://trahan.house.gov/',
title: 'Representative' },
{ name: 'David Trone',
state: 'MD',
district: '6',
party: 'D',
twitter_account: 'RepDavidTrone',
url: 'https://trone.house.gov/',
title: 'Representative' },
{ name: 'Michael Turner',
state: 'OH',
district: '10',
party: 'R',
twitter_account: 'RepMikeTurner',
url: 'https://turner.house.gov',
title: 'Representative' },
{ name: 'Lauren Underwood',
state: 'IL',
district: '14',
party: 'D',
twitter_account: 'RepUnderwood',
url: 'https://underwood.house.gov/',
title: 'Representative' },
{ name: 'Fred Upton',
state: 'MI',
district: '6',
party: 'R',
twitter_account: 'RepFredUpton',
url: 'https://upton.house.gov',
title: 'Representative' },
{ name: 'Jefferson Van Drew',
state: 'NJ',
district: '2',
party: 'D',
twitter_account: 'CongressmanJVD',
url: 'https://vandrew.house.gov/',
title: 'Representative' },
{ name: 'Juan Vargas',
state: 'CA',
district: '51',
party: 'D',
twitter_account: 'RepJuanVargas',
url: 'https://vargas.house.gov',
title: 'Representative' },
{ name: 'Marc Veasey',
state: 'TX',
district: '33',
party: 'D',
twitter_account: 'RepVeasey',
url: 'https://veasey.house.gov',
title: 'Representative' },
{ name: 'Filemon Vela',
state: 'TX',
district: '34',
party: 'D',
twitter_account: 'RepFilemonVela',
url: 'https://vela.house.gov',
title: 'Representative' },
{ name: 'Nydia Velázquez',
state: 'NY',
district: '7',
party: 'D',
twitter_account: 'NydiaVelazquez',
url: 'https://velazquez.house.gov',
title: 'Representative' },
{ name: 'Peter Visclosky',
state: 'IN',
district: '1',
party: 'D',
twitter_account: 'RepVisclosky',
url: 'https://visclosky.house.gov',
title: 'Representative' },
{ name: 'Ann Wagner',
state: 'MO',
district: '2',
party: 'R',
twitter_account: 'RepAnnWagner',
url: 'https://wagner.house.gov',
title: 'Representative' },
{ name: 'Tim Walberg',
state: 'MI',
district: '7',
party: 'R',
twitter_account: 'RepWalberg',
url: 'https://walberg.house.gov',
title: 'Representative' },
{ name: 'Greg Walden',
state: 'OR',
district: '2',
party: 'R',
twitter_account: 'RepGregWalden',
url: 'https://walden.house.gov',
title: 'Representative' },
{ name: 'Mark Walker',
state: 'NC',
district: '6',
party: 'R',
twitter_account: 'RepMarkWalker',
url: 'https://walker.house.gov',
title: 'Representative' },
{ name: 'Jackie Walorski',
state: 'IN',
district: '2',
party: 'R',
twitter_account: 'RepWalorski',
url: 'https://walorski.house.gov',
title: 'Representative' },
{ name: 'Michael Waltz',
state: 'FL',
district: '6',
party: 'R',
twitter_account: 'RepMichaelWaltz',
url: 'https://waltz.house.gov/',
title: 'Representative' },
{ name: 'Debbie Wasserman Schultz',
state: 'FL',
district: '23',
party: 'D',
twitter_account: 'RepDWStweets',
url: 'https://wassermanschultz.house.gov',
title: 'Representative' },
{ name: 'Maxine Waters',
state: 'CA',
district: '43',
party: 'D',
twitter_account: 'RepMaxineWaters',
url: 'https://waters.house.gov',
title: 'Representative' },
{ name: 'Steven Watkins',
state: 'KS',
district: '2',
party: 'R',
twitter_account: 'Rep_Watkins',
url: 'https://watkins.house.gov/',
title: 'Representative' },
{ name: 'Bonnie Watson Coleman',
state: 'NJ',
district: '12',
party: 'D',
twitter_account: 'RepBonnie',
url: 'https://watsoncoleman.house.gov',
title: 'Representative' },
{ name: 'Randy Weber',
state: 'TX',
district: '14',
party: 'R',
twitter_account: 'TXRandy14',
url: 'https://weber.house.gov',
title: 'Representative' },
{ name: 'Daniel Webster',
state: 'FL',
district: '11',
party: 'R',
twitter_account: 'RepWebster',
url: 'https://webster.house.gov',
title: 'Representative' },
{ name: 'Peter Welch',
state: 'VT',
district: 'At-Large',
party: 'D',
twitter_account: 'PeterWelch',
url: 'https://welch.house.gov',
title: 'Representative' },
{ name: 'Brad Wenstrup',
state: 'OH',
district: '2',
party: 'R',
twitter_account: 'RepBradWenstrup',
url: 'https://wenstrup.house.gov',
title: 'Representative' },
{ name: 'Bruce Westerman',
state: 'AR',
district: '4',
party: 'R',
twitter_account: 'RepWesterman',
url: 'https://westerman.house.gov',
title: 'Representative' },
{ name: 'Jennifer Wexton',
state: 'VA',
district: '10',
party: 'D',
twitter_account: 'RepWexton',
url: 'https://wexton.house.gov/',
title: 'Representative' },
{ name: 'Susan Wild',
state: 'PA',
district: '7',
party: 'D',
twitter_account: 'RepSusanWild',
url: 'https://wild.house.gov',
title: 'Representative' },
{ name: 'Roger Williams',
state: 'TX',
district: '25',
party: 'R',
twitter_account: 'RepRWilliams',
url: 'https://williams.house.gov',
title: 'Representative' },
{ name: 'Frederica Wilson',
state: 'FL',
district: '24',
party: 'D',
twitter_account: 'RepWilson',
url: 'https://wilson.house.gov',
title: 'Representative' },
{ name: 'Joe Wilson',
state: 'SC',
district: '2',
party: 'R',
twitter_account: 'RepJoeWilson',
url: 'https://joewilson.house.gov',
title: 'Representative' },
{ name: 'Robert Wittman',
state: 'VA',
district: '1',
party: 'R',
twitter_account: 'RobWittman',
url: 'https://wittman.house.gov',
title: 'Representative' },
{ name: 'Steve Womack',
state: 'AR',
district: '3',
party: 'R',
twitter_account: 'Rep_SteveWomack',
url: 'https://womack.house.gov',
title: 'Representative' },
{ name: 'Rob Woodall',
state: 'GA',
district: '7',
party: 'R',
twitter_account: 'RepRobWoodall',
url: 'https://woodall.house.gov',
title: 'Representative' },
{ name: 'Ron Wright',
state: 'TX',
district: '6',
party: 'R',
twitter_account: 'RepRonWright',
url: 'https://wright.house.gov/',
title: 'Representative' },
{ name: 'John Yarmuth',
state: 'KY',
district: '3',
party: 'D',
twitter_account: 'RepJohnYarmuth',
url: 'https://yarmuth.house.gov',
title: 'Representative' },
{ name: 'Ted Yoho',
state: 'FL',
district: '3',
party: 'R',
twitter_account: 'RepTedYoho',
url: 'https://yoho.house.gov',
title: 'Representative' },
{ name: 'Don Young',
state: 'AK',
district: 'At-Large',
party: 'R',
twitter_account: 'RepDonYoung',
url: 'https://donyoung.house.gov',
title: 'Representative' } 
]